### ISSUE TITLE
largest_k fails for transposed arrays

### ISSUE THREAD

**Issue by TheRealBazhen** [seung-lab/connected-components-3d#112]
Hi!
I faced a problem when using `largest_k` with transposed array - the result is nonsense. And during experiments with other functions (I tried `connected_components`) I did not face that problem. My cc3d version is 3.12.1

My minimal code:
```python
import numpy as np
import cc3d
import matplotlib.pyplot as plt

strange = np.load('strange.npy')

plt.imshow(cc3d.largest_k(strange.transpose(2, 1, 0), 1)[100])
plt.imshow(cc3d.largest_k(strange, 1)[:, :, 100])
plt.imshow(cc3d.connected_components(strange)[:, :, 100])
```

<img width="567" alt="image" src="https://github.com/seung-lab/connected-components-3d/assets/40463503/889b86f6-6cfa-4421-8d25-0c843fdef1ae">

<img width="537" alt="image" src="https://github.com/seung-lab/connected-components-3d/assets/40463503/5b45ad73-773d-4250-bc02-7f04766a05e3">

<img width="551" alt="image" src="https://github.com/seung-lab/connected-components-3d/assets/40463503/d6507f97-c491-42ea-88df-6ac409c79e1e">

**Comment by william-silversmith** [comment]
Hmm, I wasn't able to reproduce this with a simple test. Would you be willing to share an example image as an npy file?

**Comment by TheRealBazhen** [comment]
For sure, the file is [here](https://drive.google.com/file/d/11WOtQuFu2jDn-dBiRnG8-S41G942vV-0/view?usp=sharing)

**Comment by william-silversmith** [comment]
Thank you! I can reproduce this now.

**Comment by william-silversmith** [comment]
I found the bug. Will be fixing this!

**Comment by TheRealBazhen** [comment]
Great news, thank you!

**Comment by william-silversmith** [comment]
Released a new version. Let me know if you have any issues!
