### ISSUE TITLE
About the lastest_k function

### ISSUE THREAD

**Issue by seisen0305** [seung-lab/connected-components-3d#113]
Hello, William  
when i use lastest_k , i got some error
this is code

**import numpy as np
import cc3d
import cv2
labels_in = np.ones((512, 512, 512), dtype=np.int32)
labels_out, N = cc3d.largest_k(
  labels_in, k=10, 
  connectivity=26, 
  return_N=True,
)**

and I got **TypeError: Argument 'delta' has incorrect type (expected int, got float)**
so what can I do to reduce this error
looking forward to your answer

**Comment by william-silversmith** [comment]
Hi! I just tried running this code and did not experience the error. Do you know which version of cc3d you're running? Is it the latest version?

**Comment by seisen0305** [comment]
hello, my cc3d's version is 3.12.2,and I tried to run this code at another PC, but I have the same result as above.

**Comment by seisen0305** [comment]
I reinstall version 3.12.1, and this error has disappeared. thanks for your cc3d package, it very useful for me.

**Comment by william-silversmith** [comment]
Hi! I just noticed that the CI was failing with this error. I wrote up a fix and am pushing 3.12.3 to PyPI. Let me know if you have any more issues!
