### ISSUE TITLE
Statistics output

### ISSUE THREAD

**Issue by ckolluru** [seung-lab/connected-components-3d#114]
In this example, I expect the just one centroid near [149, 149, 149]. Could you let me know where the [64, 64, 64] comes from? Also why are the pixel indices (~149) not the same in all three dimensions with this input?

```
import numpy as np
import cc3d

labels_in = np.zeros((512, 512, 512), dtype=np.int32) 
labels_in[100:200, 100:200, 100:200] = 1
labels_out, N = cc3d.largest_k(labels_in, k = 1, connectivity = 26, delta=0, return_N = True)

a = cc3d.statistics(labels_out)
a['centroids']
```

This is what I get: 

```
array([[ 64.480415,  64.480415,  64.480415],
       [149.26369 , 149.49011 , 149.0991  ]], dtype=float32)
```

Thank you for sharing this software.

**Comment by william-silversmith** [comment]
It looks like this used to be float64 but there was a problem with memory consumption.

https://github.com/seung-lab/connected-components-3d/commit/13d7c4942d45ea612822649abc9ccda302c8799b

Hmm....

**Comment by ckolluru** [comment]
Thanks for looking into this.

If I change the test image to be ones only between [10:20, 10:20, 10:20] and zeros elsewhere the background centroid is still around [64, 64, 64]. That shouldn’t be the case right?

**Comment by william-silversmith** [comment]
That's also loss of precision and changing the foreground doesn't affect it that much since the vast majority of background pixels are black in both scenarios. When I change it to double, it gives something like the right result (256.29568989, 256.29568989, 256.29568989) which is still a bit off...

I have to figure out some way to prevent the sum from blowing up so high without sacrificing accuracy and memory efficiency.

**Comment by william-silversmith** [comment]
It was kind of tricky to figure out a method for doing this that used less memory than simply bumping to double, so I'll release a new version with that once the build completes. The precision for double is actually pretty good, I forgot to account for the large "hole" in the data before.

I'll let you know when the new version is released.

**Comment by william-silversmith** [comment]
Okay, the latest version is released and should solve the problem.

**Comment by ckolluru** [comment]
Thanks @william-silversmith!
