### ISSUE TITLE
Question on the output of contacts

### ISSUE THREAD

**Issue by tengssh** [seung-lab/connected-components-3d#116]
Hi,

Thank you for cc3d! I find it very helpful and efficient for labelling domains in 3D system.
Maybe I misunderstood the use of "contacts" function, but when I try to input a 3x3x3 array like this:
```
data = np.ones((3,3,3))
data[1,1,1]=2
labels_out = cc3d.connected_components(data, connectivity=6)
cc3d.contacts(labels_out, connectivity=6, surface_area=True)
```
and it gives me
`{(1,2): 4.0}`

Shouldn't it be 6 instead of 4, e.g. top-bottom, front-back, left-right?
Thank you!

**Comment by william-silversmith** [comment]
Yup, that looks like a bug to me. Let me check it out.

**Comment by william-silversmith** [comment]
I've just uploaded a new version to PyPI! Please give it a test and let me know if that solves it for you.

**Comment by tengssh** [comment]
Yes, it solves the problem and the results now make more sense to me.
Btw, would it be possible to implement a periodic boundary condition? I understand that experimental images may not consider it, but having this option for simulations would be cool.
Thank you again for solving this issue!

**Comment by william-silversmith** [comment]
Glad that helped!

I don't think I understand what is meant by a periodic boundary condition.
Can you elaborate?

**Comment by tengssh** [comment]
Hi,

It means that D(x)=D(x+L), where L is the length of the box along x, so that in the following case:
```
data = np.array([[3,3,0,3,3])
labels_out = cc3d.connected_components(data, connectivity=6)
```
Thereby instead of `array([[1,1,0,2,2]], dtype=unit16)` it will outpur `array([[11,0,1,1]], dtype=unit16)` is periodic boundary condition is applied.
Maybe this [wiki](https://en.wikipedia.org/wiki/Periodic_boundary_conditions) would be helpful in explaining what I meant.

**Comment by william-silversmith** [comment]
Would you need support for 6 connected only? It's a lot more tractable to support it for a limited number of connectives. I believe there are 8 separate CCL implementations in the codebase: 4, 8, 6, 18, 26, and three continuous domain versions. I don't think I'd have time to do more than a few of them.

**Comment by william-silversmith** [comment]
Might be good to continue this conversation here: https://github.com/seung-lab/connected-components-3d/issues/117

**Comment by tengssh** [comment]
> Would you need support for 6 connected only? It's a lot more tractable to support it for a limited number of connectives. I believe there are 8 separate CCL implementations in the codebase: 4, 8, 6, 18, 26, and three continuous domain versions. I don't think I'd have time to do more than a few of them.

Thank you! I think 6 should be enough.
