### ISSUE TITLE
Periodic Boundary Conditions

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/connected-components-3d#117]
> Hi,

> It means that D(x)=D(x+L), where L is the length of the box along x, so that in the following case:

> data = np.array([[3,3,0,3,3]])
> labels_out = cc3d.connected_components(data, connectivity=6)

> Thereby instead of array([[1,1,0,2,2]], dtype=unit16) it will output array([[1,1,0,1,1]], dtype=unit16) if periodic boundary condition is applied.
Maybe this [wiki](https://en.wikipedia.org/wiki/Periodic_boundary_conditions) would be helpful in explaining what I meant.

**Comment by tengssh** [comment]
A simple solution could be to post-process the labels at the edges after labelling.

**Comment by william-silversmith** [comment]
Done! Added 4 and 6 connected support to 3.13.0

**Comment by tengssh** [comment]
Great! Thank you!
