### ISSUE TITLE
Applying dust to labels does not do anything

### ISSUE THREAD

**Issue by Mohinta2892** [seung-lab/connected-components-3d#124]
Hello William,

I am trying to remove small objects via `dust` from a labelled ndarray (512^3) containing neuron segmentation instances.
I have played around with the hyper-parameters of `dust` (threshold 100-1024, my objects are between 100 to 256); connectivity 6,18,26), however, none seems to be effective in removing small  objects.

Have you seen anything like this happen before?
Any suggestions will be really appreciated.

Best,
Samia

**Comment by william-silversmith** [comment]
Hi! Would it be possible to get a sample to experiment with?

Thanks!

**Comment by Mohinta2892** [comment]
Sure, it is [here](https://www.dropbox.com/scl/fo/gl8y4nrkx2um2klfi40qc/AHsn-1Enkol6yyiatKTrweQ?rlkey=kh6lupwavzpfu3i2a76cb54w6&st=p9e2i0ro&dl=0)

**Comment by william-silversmith** [comment]
Hi Samia, 

Can you run the following code and let me know the result? I seem to be unable to reproduce your problem. There were issues with the dust function in the past, are you using the latest version of cc3d (currently version 3.16.0)?

```
import zarr
import cc3d
import numpy as np

zarray = zarr.open("hemi_x11051_y20992_z21948_merged_ids_clahed.zarr")
labels_in = zarray["volumes/labels/neuron_ids"][:]

labels_out = cc3d.dust(
 labels_in, threshold=100,
 connectivity=26, in_place=False
)

uniq, cts = np.unique(labels_out, return_counts=True)
cts = np.array([ x for x in cts if x > 0 ])
print(np.any(cts < 100))
```

Output:
```
False
```

Here's a photo of a 2d slice of removed segments:

<img width="511" alt="image" src="https://github.com/seung-lab/connected-components-3d/assets/2517065/70a44088-28d4-456e-b826-0da1948393c8">

**Comment by Mohinta2892** [comment]
Hi William,

Many thanks! You were right about the version, I had to upgrade to the latest version (3.17) and then it seems to be working.

Closing the issue now.

Best,
Samia
