### ISSUE TITLE
How to remove small object [3d volume] using cc3d.connected_components ?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/connected-components-3d#21]
How to remove small object [3d volume] using cc3d.connected_components ?

**Comment by selvakarna** [comment]
Thanks william-silversmith.

**Comment by william-silversmith** [comment]
You're welcome!

**Comment by selvakarna** [comment]
from this above code:

cc_labels = cc3d.connected_components(img)
cc_segids, pxct = np.unique(cc_labels, return_counts=True)
mask_ids = [ sid for sid, ct in zip(cc_segids, pxct) if ct < dust_threshold and sid != 0 ]
cc_labels[ np.in(cc_labels, mask_ids) ] = 0


  when i use volume image to this above code, nothing 3d small object removed ? so how to remove small 3d volume object?  @william-silversmith

**Comment by william-silversmith** [comment]
For anyone reading this thread these days, `cc3d.dust` is available as of 3.7.0 which will remove components smaller than a specified number of voxels. If you want to do something fancy like "as a fraction of the size of the largest shape" you can do passes with `cc3d.statistics` to compute it.
