### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by skamdar** [seung-lab/connected-components-3d#24]
Hi!

I have successfully installed connected-components-3d using pip.
But when I import cc3d it gives following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.pxd", line 918, in init cc3d
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Can you please help?

**Comment by william-silversmith** [comment]
Hi Sonu,

This problem arises because I compiled the binaries against a newer version of numpy (post 1.16). Try updating numpy. If you can't, try installing cc3d from source using:

```bash
pip install connected-components-3d --no-binary :all:
```

**Comment by william-silversmith** [comment]
I think I'll update the README. I think a few people are falling into this particular trap.

**Comment by skamdar** [comment]
Thanks a lot. It worked. Closing the issue.
