### ISSUE TITLE
Memory issue when i working with connected-components-3d ? volume images shape are 1000 X 1500 X 7000 ?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/connected-components-3d#28]
Memory issue when i working with connected-components-3d ? volume images shape are 1000 X 1500 X 7000 ?

**Comment by william-silversmith** [comment]
Hi Selvakarna,

Can you paste your error here? How much RAM does your machine have? I think the minimum possible RAM you'll need would be about 60 GB but probably more depending on data types and fragmentation.

Will

**Comment by selvakarna** [comment]
how to clear memory instantly ?

**Comment by william-silversmith** [comment]
The memory should be recovered the soon as the program exits. If you need to clear additional memory, you should use the task manager for your operating system to kill additional programs.

**Comment by selvakarna** [comment]
Thanks @william-silversmith,....
