### ISSUE TITLE
3d small object cannot removed when use cc3d. connected-compoenents?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/connected-components-3d#29]
3d small object cannot removed when use cc3d. connected-compoenents?:

from reference : https://github.com/seung-lab/connected-components-3d/issues/21

its not workin @william-silversmith

**Comment by william-silversmith** [comment]
The code you referenced looks correct to me. Are you sure you're getting some mask_ids back? Maybe try a bigger dust_threshold, 50 is very small. I often go as high as 1000.

**Comment by selvakarna** [comment]
Hi @william-silversmith , 
                       if i increase threshold as 10000 , its error. can you share sample code remove , unwanted small 3d volume?

**Comment by william-silversmith** [comment]
Can you share the error? The code you were using looked good to me. If you want to try something else, you can give https://github.com/seung-lab/fastremap/ a try.

**Comment by selvakarna** [comment]
Okay @william-silversmith
