### ISSUE TITLE
Pictured Example

### ISSUE THREAD

**Issue by aliakbarera** [seung-lab/connected-components-3d#34]
Will,
Thank you for this amazing work. I am new to python and the idea of CCL. The 'python use' code snippet helps to understand how the code is to be used but I would appreciate if you could please provide an example of a 3D object with multiple labels being run on your code.. 
The reason I ask is that I am currently working on a segmentation process for 3D objects and my binary matrix is (64x64x64) obtained using binvox.  I tried to read the object and then pass the (64x64x64) binary matrix into your code but I just received 1 output label. I want to verify if I am doing something wrong and if there is some more pre-processing that I need to do. 
Also the region adjacency graph is not working, there seems to be no output at all.
With so many issues that I am facing, I am sure there is something that I am doing wrong. You help would be appreciated.

**Comment by william-silversmith** [comment]
Hi Aliakbarera,

I'm glad you're finding a use for this library! Can you show me the code
you're using, the dtype of your numpy array, and its flags?

I looked on the binvox website but it wasn't obvious if it returns a bit
packed representation, uint8, or something else. cc3d doesn't currently
support bit packed arrays.

I'll see if I can find or make an example to post.

Will

**Comment by aliakbarera** [comment]
Will, Thanks for your prompt response.
I dont have much idea on the type of the binvox output but I found this piece of information on their website which I assume might provide some information about this subject matter. 

"The binary voxel data
The binary data consists of pairs of bytes. The first byte of each pair is the value byte and is either 0 or 1 (1 signifies the presence of a voxel). The second byte is the count byte and specifies how many times the preceding voxel value should be repeated (so obviously the minimum count is 1, and the maximum is 255)."

The binvox files have its own reader which can be found here 'https://github.com/dimatura/binvox-rw-py'

As for my code, I use the binvox-rw file to unpack the binvox file data and use the binary voxel information for classification. The reason I am looking to see if I can use your CCL application is to do a multiclass segmentation to further classify individual features from the voxelized files. After doing the CCL, I intend to use the watershed segmentation to classify individual features.

Ali

**Comment by william-silversmith** [comment]
If you're decoding to a numpy array, that sounds correct.

Could you share sample test data (doesn't have to be your real data, just
exhibits the error) and the surrounding code you're using? I'd be happy to
see if I can run connected components on it.

Will

**Comment by aliakbarera** [comment]
[CCL_Package.zip](https://github.com/seung-lab/connected-components-3d/files/3875957/CCL_Package.zip)

Will,
Please find attached a zip file containing a couple of binvox files to test the connectivity labeling code named 'Test.py'. I have attached 3 binvox files for your reference and the binvow_rw file that will help read and unpack the binvox files. As you might see in the Test.py, I have used your code snippet from Pypi as is with a couple of lines at the beginning to just read the binvox files using the binvow_rw.

I hope this is what you were looking for,

Ali

**Comment by william-silversmith** [comment]
Hi Ali,

I checked out the data file and ran the code. It looks like there's only a single connected component in the data (some kind of wheel or cap?). This library will detect labels separated by at least one voxel (or since you selected 18 connectivity, one voxel or only touching at the corners). Maybe you meant to run your segmentation algorithm first? That would make more sense b/c then different parts separated in space would have the same label and CCL would have something to work with.

Will

**Comment by aliakbarera** [comment]
Will, 
Thank you for trying this out for me. I would like to mention that I am currently just going by the paper attached here with this message. Again, being new to python and ML, I might have been misunderstanding but I would appreciate if you could look into the "6.3. Multi-feature recognition" part of the paper if you have some time. 

Ali
[Zhibo.pdf](https://github.com/seung-lab/connected-components-3d/files/3876168/Zhibo.pdf)

**Comment by william-silversmith** [comment]
```
6.3. Multi-feature recognition

A typical CAD component usually has multiple machining features. Often, some of those features are overlapping. But the FeatureNet was trained to identify component with single feature
only. Therefore, to enhance the utility of the proposed network and to recognize multiple overlapping features, it was augmented with a segmentation technique. First, the input CAD component is voxelized using the binvox library as discussed before.``` 

So far so good.

```
The disconnected features or disconnected subset of features are separated
from each other in the voxelized model by using connected component labeling algorithm provided in the scikit-image package [35] for Python. Next, each disconnected subset of features is segmented into single individual features using watershed segmentation algorithm [36]. 
```
In the specific case you provided, there are no disconnected features, so the CCL step is trivial. You should apply watershed to either the output of CCL or the binary directly (as they are essentially the same).

```
Finally, the single segmented features are passed as input into the trained CNN model for classification.
```
Makes sense.

**Comment by william-silversmith** [comment]
By the way, if you need a distance transform library for the preprocessing step of watershed, I wrote one: https://github.com/seung-lab/euclidean-distance-transform-3d

It also handles multiple labels. :dancer:

**Comment by aliakbarera** [comment]
Thank you for your valuable inputs.
once thing I was wondering and this might be really not a good idea but is there any way to flip the foreground and background label values. I mean is there any way to label the background of each pixel plane and keep the foreground as 0. This might somehow help in the process of labeling the features (hole, slots, etc) as per the paper. Your inputs are much appreciated.

Ali

**Comment by william-silversmith** [comment]
Oh sorry, I thought I had written a response to you but I had only done so in my head. 

This is easy to accomplish:
```python
img = ~img # for a binary image
img = L1 * (img == 0) + L2 * (img == 1) # for an arbitrary images where L1 and L2 are new labels to assign
```

**Comment by aliakbarera** [comment]
Will, 
I would like to re-iterate, I am a newbie at machine learning and python. Just to confirm, the cc3d output is "extracted image". Should I be adding this piece of the code after that or this needs to be added in one of the source codes?
I once again apologize for my ignorance.

**Comment by william-silversmith** [comment]
Hi Ali, 

The reason for the `extracted_image` code is that cc3d will label all the connected shapes in the array, but often we want to submit only one of the components at a time for further processing (as is the case in the paper you referenced). If you know the label of the component you want to manipulated, you can use: `labels_out == label` to turn it into a binary image. I then multiply it as `labels_out * (labels_out == segid)` in order to preserve the label name in the binary image, but this is not necessary. 

Will

**Comment by aliakbarera** [comment]
Will, I am sorry but I still am having an issue understanding this concept. I really apologize for the continuous back and forth and I appreciate your patience towards me. Even after doing X=~X to sort of flip the binary image, the output are just 2 labels. I am pretty sure I am doing something horribly wrong here. 
Without wasting much of your valuable time, if you can please post an example from your densely labeled 3D image for a better understanding of the inputs and outputs I will be highly obliged for the same. Hopefully that will reduce my confusion. 
Eventually, I will bother you if at all I have more questions which I am being completely honest I will. :)

**Comment by william-silversmith** [comment]
Hi Ali,

If you flip the binary image, I'm not sure that it will actually produce additional components as there didn't seem to be any fully enclosed internal holes in the object. 

However, if you're interested in seeing a densely labeled image, check out [this link](https://neuroglancer-demo.appspot.com/#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image%22%2C%22type%22:%22image%22%2C%22name%22:%22original-image%22%2C%22visible%22:false%7D%2C%7B%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image_color_corrected%22%2C%22type%22:%22image%22%2C%22name%22:%22corrected-image%22%7D%2C%7B%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/ground_truth%22%2C%22type%22:%22segmentation%22%2C%22selectedAlpha%22:0.63%2C%22notSelectedAlpha%22:0.14%2C%22segments%22:%5B%2213%22%2C%2215%22%2C%222282%22%2C%223189%22%2C%223207%22%2C%223208%22%2C%223224%22%2C%223228%22%2C%223710%22%2C%223758%22%2C%224027%22%2C%22444%22%2C%224651%22%2C%224901%22%2C%224965%22%5D%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines_and_points%22%2C%22mode3d%22:%22lines%22%7D%2C%22name%22:%22ground_truth%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B6%2C6%2C30%5D%2C%22voxelCoordinates%22:%5B5523.99072265625%2C8538.9384765625%2C1198.0423583984375%5D%7D%7D%2C%22zoomFactor%22:22.573112129999547%7D%2C%22perspectiveOrientation%22:%5B-0.0040475670248270035%2C-0.9566215872764587%2C-0.22688281536102295%2C-0.18271005153656006%5D%2C%22perspectiveZoom%22:340.35867907175077%2C%22layout%22:%224panel%22%7D). 

Check out this youtube video for an explanation of what this algorithm is doing: https://www.youtube.com/watch?v=ticZclUYy88

**Comment by aliakbarera** [comment]
William,
In the last 2 weeks, I tried a few things for component labeling. I treated my binary as 2D instead of 3d and used a 2d labeling code and flipped the background, foreground information. I was able to achieve segmentation but its not exactly what I what since now i have segmentation info along 3 separate axis and now merging them together is an issue. Please find attached, the snippet of my code and the files associated with it, What would be really helpful would be if you could please tell me how to treat foreground as background and vice versa in cc3d and I think it will complete the process. Once again I apologize for the inconvenience.
[Github.zip](https://github.com/seung-lab/connected-components-3d/files/3957362/Github.zip)

**Comment by william-silversmith** [comment]
Hi Ali,

To treat background as foreground write `~img`, but I don't think that necessarily does what you want. The 2D code broke things into multiple components because you were looking at slices of a 3D object. For example if you draw a line through a `U` shape (~U~), you'll see `. .` in the 1D projection, which would be two distinct connected components, but the `U` is a single connected component in two dimensions.

I meshed the object to get a better look at it. It looks like it has a single connected component.
![image](https://user-images.githubusercontent.com/2517065/70741874-527bee00-1cea-11ea-9462-ea2ae154169a.png)

Taking the inverse of this will give you the holes in the wheel.

**Comment by aliakbarera** [comment]
Will, you are absolutely right. Once I inverse the binary model, the out labels are still the foreground and the background. The 'disconnected component labeling' doesn't happen as I want to using cc3d. I dont know how else to approach this issue.

**Comment by william-silversmith** [comment]
I think I don't fully understand what you want to happen. Can you explain what parts of the image you'd like to see isolated?

**Comment by aliakbarera** [comment]
Will, I am attaching an image of the disconnected component labeling that I achieved with 2D labeling by inversing the foreground and background. I want this in 3D. So instead of the connected voxel labeling I want the labels to be assigned to the disconnected voxels which in my case are holes, in all 3 axes. The labeling will be further taken into segmentation and each label needs to be classified using a trained model that I have.

The image shows the 8th layer of the axis 2 of the binvox file I sent you in the last message.
![Github](https://user-images.githubusercontent.com/57166079/70745784-9a067800-1cf2-11ea-8a99-6809b4c89eaa.JPG)

**Comment by william-silversmith** [comment]
What you can do is paint another ID above and below the object. This might be easy to do with a few numpy commands like `img[:,:,:5] = 2` or some such. If hard pressed, you can manually paint individual voxels until you get a good result.

**Comment by william-silversmith** [comment]
Hi Ali, 

Let me know if this fixed things for you. I'll close this issue due to inactivity in a few days. Feel free to reopen if you need to!

Will
