### ISSUE TITLE
How to access/extract the connected components using this package ?

### ISSUE THREAD

**Issue by tkseneee** [seung-lab/connected-components-3d#4]
Thank you for making this package windows compatible. I segmented the region of interest from Lung CT scans. My segmented output size 512x512x130, where 130 is the total number of cross sectional images in the Lung CT scan and 512x512 is the size of each cross sectional image. 
I use the following code to find the connected components (connected tissue clusters) across the cross section of the CT scan.
import numpy as np
from cc3d import connected_components
nod_arr=np.load('nodule_arr.npy')
nod_3d = connected_components(nod_arr)

It doesn't throw any error, but I can't able to extract any label information from nod_3d. How can I extract the tissues clusters which are connected across the cross section of CT scan ? For example, if one tissue cluster is exist from slice number 40 to 43 (4 cross section images), I need to extract that tissue cluster alone separately.
![image](https://user-images.githubusercontent.com/42732218/51370985-d0f1ff00-1b1e-11e9-8923-476f2664ef02.png)

**Comment by william-silversmith** [comment]
Hi Senthil,

I'm glad that first step worked for you! I have a few questions about the issue to help me diagnose the problem:

1) What is the data type of the input image? 
2) What is the data type of the output image?
3) What is meant by "extract any label information"? Do you mean that the output is boolean?
4) What is the output of `nod_arr.flags`?
5) What is the output of `nod_3d.flags`?

If your issue is you need to separate the intermingled labels, here's what I'd recommend:

```python
import numpy as np

segids = np.unique(nod_3d)[1:] # [1:] skips segid 0

for segid in segids:
    isolated = nod_3d * (segid == nod_3d)
```

If you know the label of the segid, you can skip the unique and for loop steps.

**Comment by william-silversmith** [comment]
I updated the README with instructions on how to extract individual labels.

**Comment by tkseneee** [comment]
Thank you for your replies and sorry for my late response. 

```
nod_3d = connected_components(nod_arr)    
segids = np.unique(nod_3d)[1:]
```

for the above code I am getting 30846 segids.

```
segid=10 #some random id I took
p=(segid==nod_3d)
po=np.where(p==True)
iso=nod_3d*p 
```
for all the segid, I am getting 'po' values is True at only one position (x,y,z). So it means that  I am not able extract the connected components in 3D right ?.  

my nod_arr size is (512x512x130), data type is 'uint8' (also I can generate nod_arr in uint32)

nod_arr.flags output is:
C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

nod_3d.flags output is: 
 C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

**Comment by william-silversmith** [comment]
1.0.3 is live. :)
