### ISSUE TITLE
Using cc3d with multiple channels?

### ISSUE THREAD

**Issue by sneh-debug** [seung-lab/connected-components-3d#57]
hello,
I am using 3D images ,so for that how can i apply connected component library?

**Comment by william-silversmith** [comment]
Hi,

Multiple channels are not supported. I'm not totally sure what that would
mean as often the channels are interrelated and sometimes they represent
different data planes.

You can either: Run cc3d against each channel separately and recombine them
after or you can combine all the channels into a single image (say combine
RGB into a uint32 image).

If you tell me more about your data I can recommend something more specific.

Will

**Comment by sneh-debug** [comment]
hello @william-silversmith ,i want to apply cc3d on segmentation result image containing multiple class and the dimensions of result image is 128*128*128

**Comment by william-silversmith** [comment]
Here's what I suspect you want to do:

```python
# Let multichannel be the segmentation image.

output = np.zeros(multichannel.shape, dtype=np.uint32)
for i in range(multichannel.shape[3]):
   output[:,:,:,i] = cc3d.connected_components(multichannel[:,:,:,i])
```

**Comment by sneh-debug** [comment]
> Here's what I suspect you want to do:
> 
> ```python
> # Let multichannel be the segmentation image.
> 
> output = np.zeros(multichannel.shape, dtype=np.uint32)
> for i in range(multichannel.shape[3]):
>    output[:,:,:,i] = cc3d.connected_components(multichannel[:,:,:,i])
> ```
> 
> If instead by multichannel, you don't mean mean a 4D image and instead mean simply an image with multiple label types (i.e. label 1 might be adjacent to label 2), just use cc3d normally, that's what it was designed for.

Thanks
![Capture](https://user-images.githubusercontent.com/57990998/98786484-25691b80-2424-11eb-96d7-404a0320a873.PNG) 
this is 3d image showing all 3 axis, i want to apply cc3d on it. How will i pass the image to it? i have to convert it into array?

**Comment by sneh-debug** [comment]
`import cc3d
import numpy as np
import nibabel
PNii  = nibabel.load('./prediction/BraTS20_Training_368/prediction.nii.gz')
P  = PNii.get_fdata()
print(P.shape)
#multichannel='./prediction/BraTS20_Training_368/prediction.nii.gz'
output = np.zeros(P.shape, dtype=np.uint32)
for i in range(P.shape[2]):
   output[:,:,i] = cc3d.connected_components(P[:,:,i])`
I used your code but got following errors:
File "crf.py", line 10, in <module>
    output[:,:,i] = cc3d.connected_components(P[:,:,i])
  File "cc3d.pyx", line 250, in cc3d.connected_components
  File "cc3d.pyx", line 145, in cc3d.compute_zeroth_pass
TypeError: Type float64 not currently supported.

**Comment by sneh-debug** [comment]
@william-silversmith 
`
output_dir='./'
PNii  = nibabel.load('./prediction/BraTS20_Training_368/prediction.nii.gz')
P  = PNii.get_fdata()
print(P.shape)
#multichannel='./prediction/BraTS20_Training_368/prediction.nii.gz'
output = np.zeros(P.shape, dtype=np.uint32)
for i in range(P.shape[2]):
   output[:,:,i] = cc3d.connected_components(output[:,:,i])
print(output.shape)
output=sitk.GetImageFromArray(output)
  #get the save path
sitk.WriteImage(output,output_dir + 'new.nii.gz') 

`
This is my code for apply cc3d and saving it into 3d image with .nii.gz format but  the output image is blank image? Please tell me what mistake i am doing here.
Thanks

**Comment by william-silversmith** [comment]
Hi sneh, it looks like you are passing a blank output to cc3d. However, the way you're doing it you'll run connected components on each 2D slice, which may not be what you want. The following will probably produce 3D connected components if I converted P correctly.

```python
output_dir='./'
PNii  = nibabel.load('./prediction/BraTS20_Training_368/prediction.nii.gz')
P  = PNii.get_fdata() 
output = cc3d.connected_components(P)
output=sitk.GetImageFromArray(output)
sitk.WriteImage(output,output_dir + 'new.nii.gz') 
```

**Comment by sneh-debug** [comment]
> Hi sneh, it looks like you are passing a blank output to cc3d. However, the way you're doing it you'll run connected components on each 2D slice, which may not be what you want. The following will probably produce 3D connected components if P is a numpy array.
> 
> ```python
> output_dir='./'
> PNii  = nibabel.load('./prediction/BraTS20_Training_368/prediction.nii.gz')
> P  = PNii.get_fdata() 
> output = cc3d.connected_components(P)
> output=sitk.GetImageFromArray(output)
> sitk.WriteImage(output,output_dir + 'new.nii.gz') 
> ```

then it gives following error:
TypeError: Type float64 not currently supported.

**Comment by william-silversmith** [comment]
If your data is floating point, it's not supported. You'll have to find a way to convert it to integer labels. This could be as easy as `P.astype(np.uint64)`.

**Comment by sneh-debug** [comment]
@william-silversmith it worked . thank you. can we increase the intensity value? The  image obtained from cc3d is not clear, very difficult to visualize.

**Comment by william-silversmith** [comment]
I'm glad it worked! To visualize more easily, try casting the output to a float before passing it to `save_images`. That functions re-normalizes floats to be more visible.

**Comment by william-silversmith** [comment]
Closing this question due to inactivity. Please reopen if you still need help!
