### ISSUE TITLE
Label Statistics

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/connected-components-3d#75]
Would be good to have something like cv2.connectedComponentsWithStats which provides:
- Bounding box for each label
- Centroids
- Voxel Count / Volume (Vol = res * Ct)

It would be even more interesting if this could be done as a one-pass algorithm too. However, it's pretty easy to add this as an additional pass. 

Voxel count is pretty easily handled by https://github.com/seung-lab/fastremap but because we know the image statistics here, we can get some minor efficiencies. Centroids are also easy to compute (a 2d version is here: https://github.com/seung-lab/kimimaro/blob/master/ext/skeletontricks/skeletontricks.pyx#L463).

**Comment by Karol-G** [comment]
Hi William,

`cc3d.statistics` returns the lists `voxel_counts`, `bounding_boxes` and `centroids`. Does index 0 in each of the list correspond to component 1 (label 1) and so on or is it unordered? Maybe it would be better to return a list of dicts each with the entries `label`, `voxel_counts`, `bounding_boxes` and `centroids`? This would be similar to `skimage.measure.regionprops` and is in my opinion more intuitive. Also, it would make it easier to return more stats without getting to messy.

Best,
Karol

**Comment by william-silversmith** [comment]
Hi Karol,

Thanks for writing in! The index into the list is the label ID. Index 0 is the background. This is similar to scipy.measure.find_objects except that in scipy, the first index corresponds to label 1, so you need to do arr[label-1] to get the right index. There was some discussion of this here: https://github.com/seung-lab/connected-components-3d/discussions/94 I figured it would be more intuitive to not require any offset (and I was getting the statistics for label 0 anyway in one pass).

Array of objects vs object containing arrays is always debatable. I tend to favor object of arrays because then you can operate on the entire array efficiently. This is also the format used to actually perform the calculation internally for that reason (which is why the function is fast).

There might come a point when e.g. some labels might have calculated properties that others do not. I'll reconsider the interface as more properties are proposed. If there's a situation where you need statistics to be a drop-in replacement for regionprops, let me know and we can discuss some more. Maybe I could add in a compatibility function that translates the interface.

Will

**Comment by Karol-G** [comment]
Hi Will,

thanks for the quick reply! 

> Thanks for writing in! The index into the list is the label ID (e.g. arr[label] for each of the properties). Index 0 is the background. This is similar to scipy.measure.find_objects except that in scipy, the first index corresponds to label 1, so you need to do arr[label-1] to get the right index. There was some discussion of this here: https://github.com/seung-lab/connected-components-3d/discussions/94 I figured it would be more intuitive to not require any offset (and I was getting the statistics for label 0 anyway in one pass).

Ah, I didn't assume that the background was also treated as a component. Thanks for the clarification!

> Array of objects vs object containing arrays is always debatable. I tend to favor object of arrays because then you can operate on the entire array efficiently. This is also the format used to actually perform the calculation internally for that reason (which is why the function is fast).

Yes, you are right. It probably comes down to preference. I am team object-containing-array ;) but the current representation is fine as well with only three stats.

> There might come a point when e.g. some labels might have calculated properties that others do not. I'll reconsider the interface as more properties are proposed. If there's a situation where you need statistics to be a drop-in replacement for regionprops, let me know and we can discuss some more. Maybe I could add in a compatibility function that translates the interface.

At the moment, I only need the bounding boxes so the current output is absolutly sufficient. But thanks for the proposition!

Best,
Karol

**Comment by william-silversmith** [comment]
Anytime! You can always let me know if you have any questions or feedback about cc3d. Good luck on your project!

**Comment by Karol-G** [comment]
Thanks! Another question: Does the number of components, returned in `connected_components` when using the `return_N` parameter, also include the background component?

**Comment by william-silversmith** [comment]
No, it only counts foreground labels.

**Comment by Karol-G** [comment]
Thanks!
