### ISSUE TITLE
cc3d.dust fails

### ISSUE THREAD

**Issue by doiko** [seung-lab/connected-components-3d#99]
Working in Ubuntu 22.04
python 3.8
connected-components-3d==3.10.2
numpy==1.23.2

Trying 
```
labels_out = cc3d.dust(
            source_cube[i_range, x_range, s_slice], threshold=100,
            connectivity=26, in_place=False
        )
```
results to error 
```
    labels_out = cc3d.dust(
  File "cc3d.pyx", line 1070, in cc3d.dust
  File "cc3d.pyx", line 969, in cc3d.erase
  File "cc3d.pyx", line 937, in cc3d.draw
  File "cc3d.pyx", line 939, in cc3d.__pyx_fused_cpdef
TypeError: No matching signature found
```
Any idea

**Comment by william-silversmith** [comment]
Hi there, thanks for writing in!

Based on a cursory look at the code, the most likely reason for it to fail
like that is if your source cube is not an unsigned integer type. Would you
mind checking that out and let me know if that fixes it? This isn't an
obvious constraint so my apologies if that's what happened here.

Will

**Comment by doiko** [comment]
Hi Will,
You are right...
Casting to bool sorted the problem...
Please close the ticket.
Dimitris

**Comment by william-silversmith** [comment]
Glad it's working for you!
